baseURL = 'https://yuhangxyh.github.io/'
languageCode = 'en-us'
title = 'Yuhang Xu website'
theme = "hugo-bearcub"
copyright = "Yuhang Xu (CC BY 4.0)"

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
  